### ISSUE TITLE
Error `"path" argument must be of type string. Received undefined` introduced in v1.14.4

### ISSUE THREAD

**Issue by codeflorist** [leolabs/json-autotranslate#131]
I'm using `json-autotranslate` with this call:

```shell
npx json-autotranslate --source-language en --directory-structure ngx-translate  --type key-based  --decode-escapes --delete-unused-strings --service deepl-free --config <TOKEN>
```

Using a `en.json` like this:
```json
{
	"test": "example"
}
```

This was working fine using v1.14.3.

But with v1.14.4 the following error is thrown:

```
An error has occurred:
The "path" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at Object.join (node:path:433:7)
    at DeepL.runTranslation (C:\Users\<USER>\AppData\Local\npm-cache\_npx\c2e5601f47c93b16\node_modules\json-autotranslate\lib\services\deepl.js:230:39)
    at DeepL.translateStrings (C:\Users\<USER>\AppData\Local\npm-cache\_npx\c2e5601f47c93b16\node_modules\json-autotranslate\lib\services\deepl.js:123:43)
    at C:\Users\<USER>\AppData\Local\npm-cache\_npx\c2e5601f47c93b16\node_modules\json-autotranslate\lib\index.js:243:60
    at translate (C:\Users\<USER>\AppData\Local\npm-cache\_npx\c2e5601f47c93b16\node_modules\json-autotranslate\lib\index.js:184:72)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Using npx with the specifix v1.14.3 version (`npx json-autotranslate@1.14.3 ...`) is a temporary solution.

**Comment by monsieur-ricky** [comment]
Any news on this issue? What is the root cause?

**Comment by monsieur-ricky** [comment]
Well, after giving a closer look into the latest release, I saw this change in the README: `set the glossaries folder to be used by DeepL. Keep empty for automatic determination of matching glossary`.
So, adding `-g` to the command makes everything work again.

**Comment by leolabs** [comment]
Hey @monsieur-ricky, please excuse my late reply!

I've just released a new version that should fix this issue. You shouldn't have to include the `-g` option if you're not working with glossaries. 

Could you check if this 1.14.5 works for you?

**Comment by monsieur-ricky** [comment]
Hey @leolabs, no problem. Did a quick test and everything seems to be working correctly. Thanks!
