### ISSUE TITLE
Error empty other language directory

### ISSUE THREAD

**Issue by kerac2002** [leolabs/json-autotranslate#60]
When I tried to use it with:

json-autotranslate -i locales --config google_key.json -s google-translate

and I let the fr and de language directories empty I had the following error:

An error has occurred:
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at /Users/catalin/node_modules/json-autotranslate/lib/index.js:390:141
    at step (/Users/catalin/node_modules/json-autotranslate/lib/index.js:68:23)
    at Object.next (/Users/catalin/node_modules/json-autotranslate/lib/index.js:49:53)
    at fulfilled (/Users/catalin/node_modules/json-autotranslate/lib/index.js:40:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by leolabs** [comment]
This is fixed in #62 and published in v1.10.1 :)
