### ISSUE TITLE
The source language en doesn't exist.

### ISSUE THREAD

**Issue by thagxt** [leolabs/json-autotranslate#64]
I'm having troubles running this.

When I run `npx json-autotranslate`

I get this error:

```zsh
An error has occurred:
The source language en doesn't exist.
Error: The source language en doesn't exist.
    at /Users/xxx/Documents/dev/translate/node_modules/json-autotranslate/lib/index.js:129:31
    at step (/Users/xxx/Documents/dev/translate/node_modules/json-autotranslate/lib/index.js:68:23)
    at Object.next (/Users/xxx/Documents/dev/translate/node_modules/json-autotranslate/lib/index.js:49:53)
    at /Users/xxx/Documents/dev/translate/node_modules/json-autotranslate/lib/index.js:43:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/xxx/Documents/dev/translate/node_modules/json-autotranslate/lib/index.js:39:12)
    at translate (/Users/xxx/Documents/dev/translate/node_modules/json-autotranslate/lib/index.js:115:12)
    at Object.<anonymous> (/Users/xxx/Documents/dev/translate/node_modules/json-autotranslate/lib/index.js:345:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
```

I also get the same error when using yarn `yarn json-autotranslate`

```zsh
% yarn json-autotranslate
yarn run v1.22.18
warning package.json: No license field
$ /Users/xxx/Documents/dev/translate/node_modules/.bin/json-autotranslate

An error has occurred:
The source language en doesn't exist.
Error: The source language en doesn't exist.
    at /Users/xxx/Documents/dev/translate/node_modules/json-autotranslate/lib/index.js:129:31
    at step (/Users/xxx/Documents/dev/translate/node_modules/json-autotranslate/lib/index.js:68:23)
    at Object.next (/Users/xxx/Documents/dev/translate/node_modules/json-autotranslate/lib/index.js:49:53)
    at /Users/xxx/Documents/dev/translate/node_modules/json-autotranslate/lib/index.js:43:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/xxx/Documents/dev/translate/node_modules/json-autotranslate/lib/index.js:39:12)
    at translate (/Users/xxx/Documents/dev/translate/node_modules/json-autotranslate/lib/index.js:115:12)
    at Object.<anonymous> (/Users/xxx/Documents/dev/translate/node_modules/json-autotranslate/lib/index.js:345:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## I'm trying to use it with `deepl-free`

can you please show me a command to make it run with `deepl-free` with translation files inside the `locales` directory `en.default.json`

**Comment by leolabs** [comment]
json-autotranslate expects the locales directory to have one subdirectory per language. So instead of `locales/en.default.json`, your source file would need to be located at `locales/en/default.json`.

You can then run the tool with `yarn json-autotranslate -i locales -s deepl-free -c <your API key>`

I hope this helps :)

**Comment by thagxt** [comment]
Thanks a ton @leolabs for the clarification! That worked.

I've another problem/question...

My JSON is "heavily" indented...

example:
```json
{
  "general": {
    "home": "Home",
    "accessibility": {
      "success": {
        "thankYou": "Thank you. Your email was sent",
        "commentSubmitted": "Your comment was submitted."
      },
      "error": "Error:",
      "loading": "loading"
    },
    "meta": {
      "tags": "Tags",
      "page": "page"
    }
  },
```

when I try to run this thru json-autotranslate, I get a:

```zsh
An error has occurred:
Expected identifier but "{" found.
SyntaxError: Expected identifier but "{" found.
    at peg$buildStructuredError (/Users/xxx/Documents/dev/translate/node_modules/messageformat-parser/parser.js:407:12)
    at Object.peg$parse [as parse] (/Users/xxx/Documents/dev/translate/node_modules/messageformat-parser/parser.js:1978:11)
    at exports.matchIcu (/Users/xxx/Documents/dev/translate/node_modules/json-autotranslate/lib/matchers/icu.js:6:40)
    at Object.exports.replaceInterpolations (/Users/xxx/Documents/dev/translate/node_modules/json-autotranslate/lib/matchers/index.js:20:24)
    at DeepLFree.<anonymous> (/Users/xxx/Documents/dev/translate/node_modules/json-autotranslate/lib/services/deepl-free.js:119:41)
    at step (/Users/xxx/Documents/dev/translate/node_modules/json-autotranslate/lib/services/deepl-free.js:33:23)
    at Object.next (/Users/xxx/Documents/dev/translate/node_modules/json-autotranslate/lib/services/deepl-free.js:14:53)
    at /Users/xxx/Documents/dev/translate/node_modules/json-autotranslate/lib/services/deepl-free.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/xxx/Documents/dev/translate/node_modules/json-autotranslate/lib/services/deepl-free.js:4:12)
```

I suppose `json-autotranslate` isn't able to work with files that are indented that much, is that right? Is there anything I can do to make it work?

Thanks again.

**Comment by leolabs** [comment]
The tool should have no issues working with deeply-nested JSON objects, but the error message suggests that the matcher expects variables to be defined as `{variable}` in the text. If you define your variables as `{{variable}}`, then you might want to switch to i18next's matcher by adding `-m i18next` to your command.

I hope this helps :)

**Comment by thagxt** [comment]
Yes, adding `-m i18next` worked perfectly. Thank you very much for the help @leolabs.

**Comment by leolabs** [comment]
Glad I could help :)
