### ISSUE TITLE
issue with type of json with azure

### ISSUE THREAD

**Issue by johnfelipe** [leolabs/json-autotranslate#70]
[messages.zip](https://github.com/leolabs/json-autotranslate/files/8856398/messages.zip)

	Found 1 target language(s):
	-> es

	🏭 Loading source files...
	├── helper-messages.json (key-based)
	├── messages.json (key-based)
	└── Done

	✨ Initializing Azure...
	└── Done

	🔍 Looking for key-value inconsistencies in source files...
	└── No inconsistencies found

	🔍 Looking for invalid keys in source files...
	└── No invalid keys found

	💬 Translating strings from en to es...
	├── Translating helper-messages.json (+84)
	├── Translating messages.json
	An error has occurred:
	input.match is not a function
	TypeError: input.match is not a function
		at exports.matchI18Next (/root/json-autotranslate/node_modules/json-autotranslate/lib/matchers/i18next.js:5:25)
		at Object.exports.replaceInterpolations (/root/json-autotranslate/node_modules/json-autotranslate/lib/matchers/index.js:20:24)
		at /root/json-autotranslate/node_modules/json-autotranslate/lib/services/azure-translator.js:107:49
		at Array.map (<anonymous>)
		at AzureTranslator.<anonymous> (/root/json-autotranslate/node_modules/json-autotranslate/lib/services/azure-translator.js:105:45)
		at step (/root/json-autotranslate/node_modules/json-autotranslate/lib/services/azure-translator.js:33:23)
		at Object.next (/root/json-autotranslate/node_modules/json-autotranslate/lib/services/azure-translator.js:14:53)
		at /root/json-autotranslate/node_modules/json-autotranslate/lib/services/azure-translator.js:8:71
		at new Promise (<anonymous>)
		at __awaiter (/root/json-autotranslate/node_modules/json-autotranslate/lib/services/azure-translator.js:4:12)

**Comment by johnfelipe** [comment]
@leolabs r u there?

**Comment by johnfelipe** [comment]
That would be great

**Comment by johnfelipe** [comment]
> I think it has to do with the translation in line 968 in your file. This tool expects translations to be a string instead of a number. Maybe I can add a filter to skip all non-string entries in the input files.

remember im using Azure not DeepL

**Comment by leolabs** [comment]
Ah, the update I pushed was not related to this issue. I think I can take a deeper look at it on Sunday.

**Comment by johnfelipe** [comment]
dear may be i can help you, show me how update and wil send you PR, i need this ASAP for academic job, pls

**Comment by johnfelipe** [comment]
> Ah, the update I pushed was not related to this issue. I think I can take a deeper look at it on Sunday.

Hi dear can u help me for azure?

**Comment by johnfelipe** [comment]
Help pls with azure engine

**Comment by johnfelipe** [comment]
sorry for persistent. pls help me for solve that json formats and with azure engine

**Comment by johnfelipe** [comment]
Hi dear, busy?
Pls help me about Json file missed ...

**Comment by johnfelipe** [comment]
hi dear, i pull latest version and json format is actual bad translation

**Comment by johnfelipe** [comment]
anyone?

**Comment by johnfelipe** [comment]
Dear pls update asap

**Comment by johnfelipe** [comment]
> Ah, the update I pushed was not related to this issue. I think I can take a deeper look at it on Sunday.

hi dear, any progress?

**Comment by leolabs** [comment]
Hey @johnfelipe,

Unfortunately I haven't found the time to work on this yet. I can't promise a timeframe since the project is just a side project and my weeks are quite full at the moment, but I'll let you know when a new release is available.

**Comment by johnfelipe** [comment]
Dear can u update for azure, pls
