### ISSUE TITLE
Throws error with double-brackets "{{" "}}" in json

### ISSUE THREAD

**Issue by jammind** [leolabs/json-autotranslate#78]
I need to translate strings with {{ }}, which is a nesting variable symbol of the popular [i18next](https://react.i18next.com/latest/trans-component) library. Here is an example.

`  "KEY": "Words {{var1}} words {{var2}}",`

While single { } works just fine, {{ }} throws below error

```
💬 Translating strings from en to ar...
├── Translating common.json (1 changes from cache)
An error has occurred:
Expected identifier but "{" found.
SyntaxError: Expected identifier but "{" found.
    at peg$buildStructuredError (/Users/ipadtinkamo/Documents/Tinkamo/tinkamo-mono/node_modules/messageformat-parser/parser.js:407:12)
    at Object.peg$parse [as parse] (/Users/ipadtinkamo/Documents/Tinkamo/tinkamo-mono/node_modules/messageformat-parser/parser.js:1978:11)
    at exports.matchIcu (/Users/ipadtinkamo/Documents/Tinkamo/tinkamo-mono/node_modules/json-autotranslate/lib/matchers/icu.js:6:40)
    at Object.exports.replaceInterpolations (/Users/ipadtinkamo/Documents/Tinkamo/tinkamo-mono/node_modules/json-autotranslate/lib/matchers/index.js:20:24)
    at GoogleTranslate.<anonymous> (/Users/ipadtinkamo/Documents/Tinkamo/tinkamo-mono/node_modules/json-autotranslate/lib/services/google-translate.js:113:57)
    at step (/Users/ipadtinkamo/Documents/Tinkamo/tinkamo-mono/node_modules/json-autotranslate/lib/services/google-translate.js:33:23)
    at Object.next (/Users/ipadtinkamo/Documents/Tinkamo/tinkamo-mono/node_modules/json-autotranslate/lib/services/google-translate.js:14:53)
    at /Users/ipadtinkamo/Documents/Tinkamo/tinkamo-mono/node_modules/json-autotranslate/lib/services/google-translate.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/ipadtinkamo/Documents/Tinkamo/tinkamo-mono/node_modules/json-autotranslate/lib/services/google-translate.js:4:12)
```

I have to manually replace {{ }} to << >> and reverse it before / after using json-autotranslate. Please fix it if possible. Thx!

**Comment by leolabs** [comment]
Hey @jammind,

If you're using i18next syntax, you have to set a flag in json-autotranslate: `-m i18next`. This should fix your issue.

**Comment by jammind** [comment]
It seems I haven't read the update notes. You are truly amazing!!

**Comment by leolabs** [comment]
Glad I could help! :)
